<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="../style.css" />

    <title>Async Try and Catch</title>
  </head>
  <body>
    <h1>
      Async Try and Catch
      <button class="btn">Open console to see the result</button>
    </h1>
    <pre>
      <code>
        <p class="note">// With Try Catch Block</p>

        const getUsers = async () => {
          try {
            const reponse = await fetch("http://httpstat.us/404");
        
            if (!response.ok) throw new Error("Request Failed");
        
            const data = await reponse.text();
            console.log(data);
          } catch (error) {
            console.log("Error : ", error);
          }
        };
        
        <p class="note">// Without Try Catch Block Outside the function</p>
        
        const getPosts = async () => {
          const reponse = await fetch("http://httpstat.us/404");
        
          if (!response.ok) throw new Error("Request Failed");
        
          const data = await reponse.text();
          console.log(data);
        };
        
        getPosts().catch((err) => console.log(err));
        
      </code>
    </pre>
    <script src="index.js"></script>
  </body>
</html>
